version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=dogrescue24
      - DB_USER=dogrescue24
      - DB_PASSWORD=dogrescue24
    networks:
      - dogrescue24-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - dogrescue24-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dogrescue24
      - MYSQL_USER=dogrescue24
      - MYSQL_PASSWORD=dogrescue24
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dogrescue24-network

volumes:
  mysql_data:

networks:
  dogrescue24-network:
    driver: bridge 